#!/usr/bin/env python
"""Generate the TC-01..TC-06 validation table + evidence summary from artifacts.

Reads only generated results (never hand-typed numbers):
  artifacts/benchmarks/results.json               baseline benchmark
  artifacts/benchmarks_ablation_no_ml/results.json baseline grid, ML off
  artifacts/benchmarks_extended/results.json      extended benchmark v2
  artifacts/external/{px4_review_v2,alfa}/results.json  real-flight validation
Writes artifacts/validation/validation_table.md.

TC numbering assumption: one test case per challenge attack class, in the order
of the AttackType enum (the official template may number them differently).
"""

from __future__ import annotations

import json
from pathlib import Path

TCS = [
    ("TC-01", "GPS_SPOOFING", "gps_spoofing", "Navigation: GNSS position spoofing"),
    ("TC-02", "MAVLINK_ANOMALY", "mavlink_anomaly", "Communication: MAVLink protocol anomaly"),
    ("TC-03", "COMMAND_INJECTION", "command_injection", "Command & control: command injection"),
    ("TC-04", "TELEMETRY_MANIPULATION", "telemetry_manipulation", "Telemetry: value manipulation"),
    ("TC-05", "DOS", "dos", "Communication / navigation: denial of service"),
    ("TC-06", "FIRMWARE_INTEGRITY", "firmware_integrity", "Firmware: integrity violation"),
]


def _load(p: str) -> dict | None:
    f = Path(p)
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else None


def _p(x) -> str:
    return "—" if x is None else f"{100 * float(x):.1f} %"


def main() -> None:
    base = _load("artifacts/benchmarks/results.json")
    noml = _load("artifacts/benchmarks_ablation_no_ml/results.json")
    ext = _load("artifacts/benchmarks_extended/results.json")
    px4 = _load("artifacts/external/px4_review_v2/results.json")
    alfa = _load("artifacts/external/alfa/results.json")
    alfa_cal = _load("artifacts/external/alfa_calibrated/results.json")
    L = ["# Validation table TC-01 … TC-06 (generated by `scripts/make_validation_table.py`)", "",
         "Ground truth for every simulated case is the attack's configured time window "
         "(`Attack.label(t)`, never visible to the detectors); scoring is per 0.2 s decision. "
         "**All TC results are simulation results.** Real-flight data (below) provides false-alarm "
         "and fault-reaction evidence only — no real attack data was available.", "",
         "| TC | Scenario | Baseline recall / precision (grace 5 s) | Baseline time-to-detect (s, mean) | "
         "Baseline recall, ML off | v2 modes: sessions detected | v2 decision recall per mode | Known limitations |",
         "|---|---|---|---|---|---|---|---|"]
    for tc, cls, key, desc in TCS:
        b = base["per_attack"].get(cls, {}) if base else {}
        lat = (base or {}).get("per_attack_detection_latency_s", {}).get(key, {})
        nm = noml["per_attack"].get(cls, {}) if noml else {}
        modes = {k: v for k, v in (ext or {}).get("per_mode", {}).items() if k.startswith(key + ":")}
        det = "; ".join(f"`{k.split(':')[1]}` {v['sessions_detected']}/{v['sessions']}" for k, v in modes.items())
        rec = "; ".join(f"`{k.split(':')[1]}` {_p(v['decision_recall'])}" for k, v in modes.items())
        lim = {
            "TC-01": "constant offset only caught at the jump; real autopilot EKF fuses GNSS, so the pos/vel residual loses independence on a real link",
            "TC-02": "thresholds tied to the simulator's 28 msg/s profile; sequence rule brittle to reordering",
            "TC-03": "replay from the legitimate GCS id undetectable without MAVLink-2 signing (gcs_replay)",
            "TC-04": "frozen attitude only visible while the vehicle turns; GPS/baro and GPS/VFR checks are degenerate on real PX4/ArduPilot telemetry (same estimator)",
            "TC-05": "GNSS jamming scored under DOS; DoS vs MAVLink-anomaly attribution often confused (latency, packet loss); link thresholds not calibrated to real radios",
            "TC-06": "manifest is unsigned; detection = SHA-256 compare (latency set by the 1 s re-check)",
        }[tc]
        L.append(f"| {tc} | {desc} | {_p(b.get('recall'))} / {_p(b.get('precision'))} | "
                 f"{lat.get('mean', '—')} | {_p(nm.get('recall'))} | {det or '—'} | {rec or '—'} | {lim} |")
    L += ["", "## Overall", "",
          "| Evidence | Decisions | Accuracy | Recall | FPR | Source |", "|---|---|---|---|---|---|"]
    if base:
        bb = base["binary"]
        L.append(f"| Baseline benchmark (fused IDS, sim) | {base['n_decisions']} | {bb['accuracy']} | "
                 f"{bb['recall_tpr']} | {bb['fpr']} | `artifacts/benchmarks/summary.md` |")
    if noml:
        bb = noml["binary"]
        L.append(f"| Baseline grid, ML off (sim) | {noml['n_decisions']} | {bb['accuracy']} | "
                 f"{bb['recall_tpr']} | {bb['fpr']} | `artifacts/benchmarks_ablation_no_ml/summary.md` |")
    if ext:
        for k, lab in (("binary_grace5", "v2, 5 s grace"), ("binary_grace0", "v2, no grace"),
                       ("binary_grace0_excl_firmware", "v2, no grace, excl. firmware")):
            bb = ext[k]
            L.append(f"| Extended benchmark {lab} (sim) | {bb['n']} | {bb['accuracy']:.4f} | "
                     f"{bb['recall']:.4f} | {bb['fpr']:.4f} | `artifacts/benchmarks_extended/summary.md` |")
    if px4:
        m = px4["mappings"]
        for mp in ("px4_telemetry", "independent_sensors_biascorr"):
            r = m.get(mp, {}).get("rates", {})
            pr = r.get("physics_trigger_rate", {})
            L.append(f"| Real PX4 flights ({m.get(mp, {}).get('n_usable_flights', 0)} flights, mapping `{mp}`): "
                     f"physics-detector alarm rate | {r.get('n_airborne_ticks', 0)} | — | — | "
                     f"{_p(pr.get('pooled'))} | `artifacts/external/px4_review_v2/summary.md` |")
    if alfa:
        c = alfa["categories"]["benign_gt"]
        L.append(f"| Real ALFA MAVLink link, author-labelled benign periods: fused-IDS alarm rate | "
                 f"{c['n_decisions']} | — | — | {_p(c.get('threat_rate'))} | `artifacts/external/alfa/summary.md` |")
    if alfa_cal:
        c = alfa_cal["categories"]["benign_gt"]
        L.append(f"| Real ALFA link, held-out dates, 1-parameter rate calibration, ML off: fused alarm rate "
                 f"on author-labelled benign periods | {c['n_decisions']} | — | — | {_p(c.get('threat_rate'))} | "
                 f"`artifacts/external/alfa_calibrated/summary.md` |")
        fe = alfa_cal["fault_event_summary"]
        L.append(f"| Same, real **physical-fault** events with any alarm after onset | "
                 f"{fe['n_with_telemetry']} events | — | {fe['detected_any_threat']}/{fe['n_with_telemetry']} | — | "
                 f"`artifacts/external/alfa_calibrated/summary.md` |")
    out = Path("artifacts/validation")
    out.mkdir(parents=True, exist_ok=True)
    (out / "validation_table.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", out / "validation_table.md")


if __name__ == "__main__":
    main()
